services:
  - type: web
    name: dhevinstech-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn WorkFlowProject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9